import { defineConfig } from "tsup";

export default defineConfig({
	entry: [
		"src/index.ts",
		"src/accounting/index.ts",
		"src/analytics/index.ts",
		"src/auth/index.ts",
		"src/backtest/index.ts",
		"src/context/index.ts",
		"src/ctf/index.ts",
		"src/events/index.ts",
		"src/execution/index.ts",
		"src/lifecycle/index.ts",
		"src/market/index.ts",
		"src/observability/index.ts",
		"src/order/index.ts",
		"src/persistence/index.ts",
		"src/position/index.ts",
		"src/pricing/index.ts",
		"src/risk/index.ts",
		"src/shared/index.ts",
		"src/signal/index.ts",
		"src/sizing/index.ts",
		"src/smart-money/index.ts",
		"src/strategy/index.ts",
		"src/websocket/index.ts",
	],
	format: ["esm", "cjs"],
	dts: true,
	splitting: true,
	sourcemap: true,
	clean: true,
	treeshake: true,
	minify: false,
});
